# Site settings
name: Jasim Afnan Predhanekar
title: Jasim | DevOps Engineer
description: I'm Jasim Afnan Predhanekar, a versatile tech enthusiast with a passion for DevOps, Cloud and Analytics.
url: https://afnanjasim.github.io/
baseurl: ''
email: afnannjasim@gmail.com
cover: https://afnanjasim.github.io/img/og.png
logo: https://afnanjasim.github.io/img/emojis/technologist.png
resume: https://afnanjasim.github.io/resume.pdf
social:
  - title: email
    url: mailto:afnannjasim@gmail.com
  - title: github
    url: https://github.com/afnanjasim
  - title: linkedin
    url: https://www.linkedin.com/in/afnanjasim

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
